env:
  MONGO_URL: ""

replicaCount: 2

probes:
  enabled: true
  path: /api/status/info
  headers: {}
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

ingress:
  hosts:
    - evergreen.devprod-evergreen.prod.corp.mongodb.com

resources:
  requests:
    cpu: 3
    memory: 8Gi
  limits:
    cpu: 6
    memory: 16Gi
